# Generated by Django 4.2.1 on 2023-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='montiria',
            new_name='monitoria',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='monitoria',
            new_name='valMonitoria',
        ),
        migrations.RenameField(
            model_name='taller',
            old_name='idEstudiante',
            new_name='idEpik',
        ),
        migrations.AddField(
            model_name='general',
            name='valTaller',
            field=models.BooleanField(default=False),
        ),
    ]
