# Generated by Django 4.2.1 on 2023-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_montiria_monitoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoria',
            old_name='FechaMonitoria',
            new_name='fechaAsistencia',
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='nombreMonitor',
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='validado',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fechaEntrega',
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='idEpik',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
